internal/backend.go, internal/data.go
=> Prevent fan stop

go.mod, internal/backend.go, internal/data.go
remember original pwm_enabled value per fan
added signal handler to restore fan configurations when exiting
fixed inverted error comparison
removed unused code
fixes #3
=> Exit behaviour

README.md, cmd/root.go, fan2go.yaml, internal/backend.go, internal/config.go, internal/data.go
use rolling window for rpm values to detect stalling fans
added config validation method
refactoring
fixes #5
=> Improved fan stall handling

README.md, cmd/root.go, go.mod, internal/backend.go, internal/persistence.go, internal/ui/logging.go, internal/ui/logging_test.go, internal/util/file.go, internal/util/math.go
Contributes to #31
* adds colored and styled cli output through [pterm](https://github.com/pterm/pterm)
* adds `--no-color` and `--no-style` cli arguments
* adds "fan2go" header when starting the daemon
=> Feature/#31 terminal UI

cmd/curve.go, internal/fans/hwmon.go, internal/hwmon/hwmon.go
=> Empty list bugfix

internal/fans/hwmon.go
=> add path sanitization

internal/hwmon/hwmon.go
=> increment index, even if pwm output cant be found

internal/controller/controller.go
=> remember original pwm value and restore it when exiting

internal/controller/controller.go, internal/controller/controller_test.go, internal/persistence/persistence.go
fixes #132 
persistence is not the most elegant, but it works TM
=> persist pwmMap

cmd/config/validate.go, cmd/curve/list.go, cmd/fan/curve.go, cmd/fan/fan.go, cmd/root.go, cmd/sensor/sensor.go, internal/configuration/config.go
=> fix config validation not working then specifying a config via -c

cmd/curve/curve.go, cmd/curve/list.go, cmd/fan/fan.go, cmd/sensor/sensor.go
Print available options if passing an unknown value for the `--id` parameter:
```
> sudo fan2go fan --id X speed 255
...
No fan with id found: X, options: [cpu in_front out_back]
```
fixes #182
=> Improve help

cmd/curve/list.go, cmd/fan/curve.go, cmd/fan/fan.go, cmd/sensor/sensor.go, internal/backend.go, internal/configuration/config.go, internal/ui/logging.go
=> less verbose CLI output

internal/configuration/config.go
=> reset Configuration data before unmarshalling the config

README.md
=> fix wrong documentation

internal/controller/controller.go, internal/controller/controller_test.go
=> fix pwmMap not beeing applied correctly, added documentation

go.mod, go.sum, internal/fans/file.go, internal/util/file.go
=> atomic file writes for file fan

internal/control_loop/direct.go, internal/control_loop/direct_test.go
=> reworked DirectControlLoop to fix custom values for "maxPwmChangePerCycle"

internal/hwmon/hwmon.go
=> fix i2c identifier

cmd/curve/list.go, cmd/fan/curve.go, cmd/fan/init.go, cmd/fan/reset.go, internal/controller/controller.go, internal/controller/controller_test.go, internal/curves/functional.go, internal/curves/linear.go, internal/fans/cmd_test.go, internal/fans/file.go, internal/fans/file_test.go, internal/fans/hwmon_test.go, internal/persistence/persistence.go, internal/persistence/persistence_test.go, internal/util/math.go, internal/util/math_test.go
=> separate pwmMap and setPwmToGetPwmMap

README.md, cmd/detect.go, cmd/fan/fan.go, cmd/sensor/sensor.go, fan2go.yaml, go.mod, go.sum, internal/backend.go, internal/configuration/fancontroller.go, internal/configuration/fans.go, internal/configuration/sensors.go, internal/configuration/validation.go, internal/configuration/validation_test.go, internal/controller/controller.go, internal/fans/common.go, internal/fans/nvidia.go, internal/nvidia/nvidia.go, internal/nvidia_base/nvidia_base.go, internal/sensors/common.go, internal/sensors/nvidia.go, main.go
I think most of the work is done, but one crucial part is missing: I'm not sure how to get nvml.Device into NvidiaFan and NvidiaSensor
Fixes #103
=> Support nvidia GPUs using go-nvml

README.md, cmd/detect.go, internal/controller/controller_test.go, internal/fans/cmd.go, internal/fans/cmd_test.go, internal/fans/common.go, internal/fans/file.go, internal/fans/file_test.go, internal/fans/hwmon.go, internal/fans/hwmon_test.go, internal/fans/nvidia.go
=> print Control "Mode" instead of only "Auto"

internal/controller/controller.go
avoid crash if rpm data is nil
automatically run initialization sequence for NvidiaFan type fans
fixes #397
=> Crash if RPM data is nil

Makefile
=> add default make target
